openapi: "3.0.0"
info:
  version: 0.0.1
  title: PLTT API
servers:
  - url: http://127.0.0.1:23456
tags:
- name: "pltt"
  description: "PLTT API list"
paths:
  /item/{jobID}:
    get:
      tags:
      - "pltt"
      summary: Get item using job ID
      parameters:
        - in: path
          name: jobID
          schema:
            type: integer
          required: true
          description: Job ID
      responses:
        "201":
          description: Successfully Call
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  jobID: 1
                  status: "completed"
                  address: "0xA92F67fB7Bdd8C3727333ce43b4c630d200ce424"
                  failReason: ""
    post:
      tags:
      - "pltt"
      summary: Create Item job for deploying contract
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shid:
                  $ref: '#/definitions/shid'
                organizationID:
                  $ref: '#/definitions/organizationID'
                organizationName:
                  $ref: '#/definitions/organizationName'
                title:
                  $ref: '#/definitions/title'
                sourceList:
                  $ref: '#/definitions/sourceList'
                producedNumber:
                  $ref: '#/definitions/producedNumber'
                producedDate:
                  $ref: '#/definitions/producedDate'
                expirationDate:
                  $ref: '#/definitions/expirationDate'
                packNumber:
                  $ref: '#/definitions/packNumber'
                unit:
                  $ref: '#/definitions/unit'
      responses:
        "201":
          description: Successfully Call
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  jobID: 1
                  status: "active"
    put:
      tags:
      - "pltt"
      summary: Update Item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shid:
                  $ref: '#/definitions/shid'
                organizationID:
                  $ref: '#/definitions/organizationID'
                organizationName:
                  $ref: '#/definitions/organizationName'
                title:
                  $ref: '#/definitions/title'
                sourceList:
                  $ref: '#/definitions/sourceList'
                producedNumber:
                  $ref: '#/definitions/producedNumber'
                producedDate:
                  $ref: '#/definitions/producedDate'
                expirationDate:
                  $ref: '#/definitions/expirationDate'
                restNumber:
                  $ref: '#/definitions/restNumber'
                packNumber:
                  $ref: '#/definitions/packNumber'
                unit:
                  $ref: '#/definitions/unit'
      responses:
        "201":
          description: Successfully Call
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  jobID: 1
                  status: "active"
  /procedure:
    get:
      tags:
      - "pltt"
      summary: Get item using job ID
      parameters:
        - in: path
          name: jobID
          schema:
            type: integer
          required: true
          description: Job ID
      responses:
        "201":
          description: Successfully Call
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  jobID: 1
                  status: "completed"
                  address: "0xA92F67fB7Bdd8C3727333ce43b4c630d200ce424"
                  failReason: ""
    post:
      tags:
      - "pltt"
      summary: Add a procedure to a item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shid:
                  $ref: '#/definitions/shid'
                procedureID:
                  $ref: '#/definitions/procedureID'
                procedureName:
                  $ref: '#/definitions/procedureName'
                startTime:
                  $ref: '#/definitions/startTime'
                endTime:
                  $ref: '#/definitions/endTime'
                mediaList:
                  $ref: '#/definitions/mediaList'
                sensorDataURLs:
                  $ref: '#/definitions/sensorDataURLs'
      responses:
        "201":
          description: Successfully Call
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  jobID: 1
                  status: "active"
  /product:
    post:
      tags:
      - "pltt"
      summary: Transact a Object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shid:
                  $ref: '#/definitions/shid'
                phid:
                  $ref: '#/definitions/phid'
                organizationID:
                  $ref: '#/definitions/organizationID'
                organizationName:
                  $ref: '#/definitions/organizationName'
                ownerID:
                  $ref: '#/definitions/ownerID'
                ownerName:
                  $ref: '#/definitions/ownerName'
                soldNumber:
                  $ref: '#/definitions/soldNumber'
                soldPack:
                  $ref: '#/definitions/soldPack'
                transactionDate:
                  $ref: '#/definitions/transactionDate'
      responses:
        "201":
          description: Successfully Call
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  msg: "Success"
        "400":
          description: User Body Error
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  msg: "Missing SHID o PHID"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  msg: "Internal Server Error"
    put:
      tags:
      - "pltt"
      summary: Update Object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shid:
                  $ref: '#/definitions/shid'
                phid:
                  $ref: '#/definitions/phid'
                organizationID:
                  $ref: '#/definitions/organizationID'
                organizationName:
                  $ref: '#/definitions/organizationName'
                ownerID:
                  $ref: '#/definitions/ownerID'
                ownerName:
                  $ref: '#/definitions/ownerName'
                soldNumber:
                  $ref: '#/definitions/soldNumber'
                soldPack:
                  $ref: '#/definitions/soldPack'
                transactionDate:
                  $ref: '#/definitions/transactionDate'
      responses:
        "201":
          description: Successfully Call
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  msg: "Success"
        "400":
          description: User Body Error
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  msg: "Missing SHID or PHID"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                type: object
                propertires:
                example:
                  msg: "Internal Server Error"
definitions:
  shid:
    name: shid
    description: Single History ID
    example: 133450
  phid:
    name: phid
    description: Product History ID
    example: 47246
  organizationID: 
    name: organizationID
    description: Orgnization ID
    example: 1234
  organizationName: 
    name: organizationName
    description: Orgnization Name
    example: "8D Tea"
  procedureID:
    name: procedureID
    description: Procedure ID
    example: 2345
  ownerID:
    name: ownerID
    description: Procedure ID
    example: 23456
  ownerName: 
    name: ownerName
    description: Owner Name
    example: "一般消費者"
  procedureName:
    name: procedureName
    description: procedure Name
    example: "原料倉領貨作業(原料倉)"
  title:
    example: "紅茶 (茶湯)"
  sourceList:
    type: array
    items:
      type: object
      properties:
        shid:
          $ref: '#/definitions/shid'
        phid:
          $ref: '#/definitions/phid'
        usedNumber:
          type: string
          example: 1122
    example: [{"shid": 1234, "phid": 12345, "number": 200}, {"shid": 5555, "phid": 12234, "number": 500}]
  producedNumber: 
    example: 15000
  packNumber: 
    example: 15
  soldNumber: 
    example: 5000
  soldPack: 
    example: 5
  restNumber:
    example:  10000
  restNumber2:
    example:  15000
  unit:
    example: "ML"
  producedDate:
    example: "2020-11-01 16:43:04"
  expirationDate:
    example: "2020-11-06 16:43:04"
  startTime:
    example: "2020-11-22 16:43:04"
  endTime:
    example: "2020-11-23 16:43:04"
  transactionDate:
    example: "2020-12-21 16:43:17"
  mediaList:
    example: ["https://s3.hicloud.net.tw/foodcloud/nvr/908/133092.mp4"]
  sensorDataURLs:
    type: array
    example: ["https://s3.hicloud.net.tw/foodcloud/data/102834908235.zip"]
  txid:
    examlpe: "0xca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb"
  lastTx:
    example: null
  nextTx:
    examlpe: "0x5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5"